version: '3.8'

services:
  server:
    # depends_on:
    #   - db
    image: '${DOCKER_IMAGE}:latest'
    container_name: zen-system-api
    restart: always
    ports:
      - '${ZEN_PORT}:${ZEN_PORT}'
    env_file:
      - .env

  # volumes:
  #   zen-system-db:
